apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replica
  labels:
    app: myapplicationreplica
    type: frontend
spec:
  template:
     metadata:
       name: my-pod
       labels:
         app: my-app
     spec:
      containers:
        - image: nginx
          name: nginx-container
  replicas: 3
      


