apiVersion: batch/v1
kind: CronJob
metadata:
  name: calc-cron-jobs
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
          containers:
            - image: ubuntu
              name:  calculator
              command: ['expr' , '3' ,'+' ,'2']
          restartPolicy: Never
