apiVersion: batch/v1
kind: Job
metadata:
  name:  random-jobs
spec:
  completions: 3
  template:
    spec:
      containers:
        - image: kodekloud/random-error
          name:  random
          command: ['expr' , '3' ,'+' ,'2']
      restartPolicy: Never