apiVersion: v1
kind: Pod
metadata:
  name: calc
spec:
  containers:
    - image: ubuntu
      name:  calculator
      command: ['expr' , '3' ,'+' ,'2']
  restartPolicy: Never
# restart policy is by default always so it tries to run container always