apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
    - image: nginx:alpine
      name: nginx-container
      volumeMounts:
        - name: vol1
          mountPath: /usr/share/nginx/html
  volumes:
    - name: vol1
      hostPath:
        path: /tmp/data

