apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc2
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
