apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc9
spec:
  resources:
    requests:
      storage: 9Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
